import React, { useState } from 'react'
// import TextBox, { TextBoxProps } from "../../src/components/textbox";
// import DatePicker, { DatePickerProps } from "../../src/components/datepicker";
// import Table, { ColumnProps, TableProps, RowSelectionProps } from "../../src/components/table";
import {
  TextBox,
  TextBoxProps,
  DatePicker,
  DatePickerProps,
  ColumnProps,
  TableProps,
  RowSelectionProps,
  Table,
} from 'agog-things'

const App = () => {
  const [state, setState] = useState({
    nameSurname: '',
    birthYear: '',
    birthDate: '',
  })

  const txtNameSurname: TextBoxProps = {
    label: 'Name Surname',
    type: 'text',
    value: state.nameSurname,
    placeholder: 'Your name and surname',
    onChange: (value) => setState({ ...state, nameSurname: value }),
  }

  const txtBirthYear: TextBoxProps = {
    label: 'Birthyear',
    type: 'number',
    value: state.birthYear,
    placeholder: 'Your birthyear',
    onChange: (value) => setState({ ...state, birthYear: value }),
  }

  const dpBirthDate: DatePickerProps = {
    lang: navigator.language,
    format: 'DD-MM-YYYY',
    label: 'Birthdate',
    value: state.birthDate,
    placeholder: 'Your birth date',
    onChange: (value) => setState({ ...state, birthDate: value }),
  }

  const columns: ColumnProps = [
    {
      title: 'Name',
      width: 150,
      key: 'first_name',
      isSorted: true,
      isFiltered: true,
      fixed: 'left',
    },
    {
      title: 'Surname',
      width: 100,
      key: 'last_name',
      isSorted: true,
      isFiltered: true,
      fixed: 'left',
    },
    {
      title: 'E mail',
      key: 'email',
      isFiltered: true,
      width: 150,
    },
    {
      title: 'Gender',
      key: 'gender',
      width: 150,
    },
    {
      title: 'IP Address',
      key: 'ip_address',
      width: 150,
    },
    {
      title: 'Age',
      key: 'age',
      width: 150,
    },
    {
      title: 'Action',
      key: 'operation',
      fixed: 'right',
      width: 100,
      render: (item: any) => <span>Selam {item.name}</span>,
    },
  ]

  interface DataType {
    id: number
    first_name: string
    last_name: string
    email: string
    gender: string
    ip_address: string
    age: number
  }

  const data: DataType[] = [
    {
      id: 1,
      first_name: 'Gregg',
      last_name: 'Harbron',
      email: 'gharbron0@who.int',
      gender: 'Male',
      ip_address: '179.22.243.67',
      age: 87,
    },
    {
      id: 2,
      first_name: 'Delbert',
      last_name: 'Bold',
      email: 'dbold1@huffingtonpost.com',
      gender: 'Male',
      ip_address: '195.74.252.2',
      age: 99,
    },
    {
      id: 3,
      first_name: 'Mechelle',
      last_name: 'Ninotti',
      email: 'mninotti2@buzzfeed.com',
      gender: 'Female',
      ip_address: '29.215.60.116',
      age: 93,
    },
    {
      id: 4,
      first_name: 'Meir',
      last_name: 'Ingham',
      email: 'mingham3@ucoz.ru',
      gender: 'Male',
      ip_address: '11.135.215.20',
      age: 7,
    },
    {
      id: 5,
      first_name: 'Tomkin',
      last_name: 'Silvers',
      email: 'tsilvers4@freewebs.com',
      gender: 'Male',
      ip_address: '218.128.192.100',
      age: 85,
    },
    {
      id: 6,
      first_name: 'Georgette',
      last_name: 'Durnall',
      email: 'gdurnall5@ebay.com',
      gender: 'Female',
      ip_address: '158.66.244.228',
      age: 34,
    },
    {
      id: 7,
      first_name: 'Aylmar',
      last_name: 'Caldaro',
      email: 'acaldaro6@dmoz.org',
      gender: 'Male',
      ip_address: '25.36.203.216',
      age: 7,
    },
    {
      id: 8,
      first_name: 'Rafferty',
      last_name: 'Varker',
      email: 'rvarker7@vk.com',
      gender: 'Male',
      ip_address: '5.169.253.193',
      age: 90,
    },
    {
      id: 9,
      first_name: 'Emory',
      last_name: 'Cheake',
      email: 'echeake8@dell.com',
      gender: 'Male',
      ip_address: '81.74.139.210',
      age: 64,
    },
    {
      id: 10,
      first_name: 'Molly',
      last_name: 'Longhorn',
      email: 'mlonghorn9@irs.gov',
      gender: 'Female',
      ip_address: '140.8.28.171',
      age: 1,
    },
    {
      id: 11,
      first_name: 'Katheryn',
      last_name: 'Robion',
      email: 'krobiona@prweb.com',
      gender: 'Genderqueer',
      ip_address: '7.191.126.44',
      age: 23,
    },
    {
      id: 12,
      first_name: 'Marlyn',
      last_name: 'Jackes',
      email: 'mjackesb@ezinearticles.com',
      gender: 'Female',
      ip_address: '48.79.14.222',
      age: 73,
    },
    {
      id: 13,
      first_name: 'Allegra',
      last_name: 'McGuffie',
      email: 'amcguffiec@timesonline.co.uk',
      gender: 'Female',
      ip_address: '67.155.58.132',
      age: 100,
    },
    {
      id: 14,
      first_name: 'Garner',
      last_name: 'Pinney',
      email: 'gpinneyd@army.mil',
      gender: 'Male',
      ip_address: '56.14.151.196',
      age: 87,
    },
    {
      id: 15,
      first_name: 'Rutter',
      last_name: 'MacNeice',
      email: 'rmacneicee@phoca.cz',
      gender: 'Male',
      ip_address: '156.139.222.57',
      age: 18,
    },
    {
      id: 16,
      first_name: 'Crissy',
      last_name: 'Diver',
      email: 'cdiverf@earthlink.net',
      gender: 'Female',
      ip_address: '29.242.155.105',
      age: 15,
    },
    {
      id: 17,
      first_name: 'Fionnula',
      last_name: 'Donson',
      email: 'fdonsong@state.tx.us',
      gender: 'Female',
      ip_address: '21.109.215.254',
      age: 100,
    },
    {
      id: 18,
      first_name: 'Meredith',
      last_name: 'Fisbey',
      email: 'mfisbeyh@macromedia.com',
      gender: 'Male',
      ip_address: '12.73.53.59',
      age: 60,
    },
    {
      id: 19,
      first_name: 'Zachary',
      last_name: 'Newgrosh',
      email: 'znewgroshi@sciencedirect.com',
      gender: 'Male',
      ip_address: '10.212.105.21',
      age: 49,
    },
    {
      id: 20,
      first_name: 'Lynne',
      last_name: 'Comar',
      email: 'lcomarj@alexa.com',
      gender: 'Female',
      ip_address: '223.203.167.38',
      age: 72,
    },
    {
      id: 21,
      first_name: 'Franchot',
      last_name: 'Ballendine',
      email: 'fballendinek@archive.org',
      gender: 'Male',
      ip_address: '232.44.57.177',
      age: 74,
    },
    {
      id: 22,
      first_name: 'Aprilette',
      last_name: 'Eger',
      email: 'aegerl@pen.io',
      gender: 'Female',
      ip_address: '161.209.167.69',
      age: 38,
    },
    {
      id: 23,
      first_name: 'Lothario',
      last_name: 'Alfonsetti',
      email: 'lalfonsettim@4shared.com',
      gender: 'Male',
      ip_address: '138.51.186.96',
      age: 99,
    },
    {
      id: 24,
      first_name: 'Minor',
      last_name: 'Penhall',
      email: 'mpenhalln@themeforest.net',
      gender: 'Male',
      ip_address: '28.105.107.70',
      age: 60,
    },
    {
      id: 25,
      first_name: 'Eben',
      last_name: 'Joust',
      email: 'ejousto@tumblr.com',
      gender: 'Male',
      ip_address: '255.158.0.237',
      age: 34,
    },
    {
      id: 26,
      first_name: 'Cherida',
      last_name: 'Portigall',
      email: 'cportigallp@goodreads.com',
      gender: 'Female',
      ip_address: '97.184.191.254',
      age: 8,
    },
    {
      id: 27,
      first_name: 'Sallie',
      last_name: 'Lamps',
      email: 'slampsq@nih.gov',
      gender: 'Female',
      ip_address: '230.2.46.62',
      age: 95,
    },
    {
      id: 28,
      first_name: 'Dallis',
      last_name: 'Mancell',
      email: 'dmancellr@slashdot.org',
      gender: 'Male',
      ip_address: '38.155.176.12',
      age: 78,
    },
    {
      id: 29,
      first_name: 'Jaymee',
      last_name: 'Parlot',
      email: 'jparlots@wp.com',
      gender: 'Female',
      ip_address: '244.135.26.36',
      age: 60,
    },
    {
      id: 30,
      first_name: 'Hayward',
      last_name: 'Hinckes',
      email: 'hhinckest@google.com.br',
      gender: 'Male',
      ip_address: '42.229.65.133',
      age: 99,
    },
    {
      id: 31,
      first_name: 'Aryn',
      last_name: 'Scamerdine',
      email: 'ascamerdineu@netscape.com',
      gender: 'Female',
      ip_address: '128.32.122.76',
      age: 30,
    },
    {
      id: 32,
      first_name: 'Cyrillus',
      last_name: 'Harbage',
      email: 'charbagev@hhs.gov',
      gender: 'Male',
      ip_address: '197.61.27.41',
      age: 100,
    },
    {
      id: 33,
      first_name: 'Estevan',
      last_name: 'McKeaney',
      email: 'emckeaneyw@spotify.com',
      gender: 'Male',
      ip_address: '21.203.23.206',
      age: 54,
    },
    {
      id: 34,
      first_name: 'Keen',
      last_name: 'Buzza',
      email: 'kbuzzax@buzzfeed.com',
      gender: 'Agender',
      ip_address: '16.46.130.197',
      age: 86,
    },
    {
      id: 35,
      first_name: 'Nanine',
      last_name: 'Charon',
      email: 'ncharony@reverbnation.com',
      gender: 'Female',
      ip_address: '211.149.68.218',
      age: 63,
    },
    {
      id: 36,
      first_name: 'Hadria',
      last_name: 'Turfs',
      email: 'hturfsz@eepurl.com',
      gender: 'Female',
      ip_address: '0.37.203.82',
      age: 16,
    },
    {
      id: 37,
      first_name: 'Fidel',
      last_name: 'Jahnig',
      email: 'fjahnig10@ox.ac.uk',
      gender: 'Male',
      ip_address: '158.98.139.169',
      age: 18,
    },
    {
      id: 38,
      first_name: 'Eugenio',
      last_name: 'Huncote',
      email: 'ehuncote11@discuz.net',
      gender: 'Male',
      ip_address: '39.2.72.242',
      age: 42,
    },
    {
      id: 39,
      first_name: 'Carolyne',
      last_name: 'Scroggie',
      email: 'cscroggie12@networksolutions.com',
      gender: 'Female',
      ip_address: '150.60.65.244',
      age: 81,
    },
    {
      id: 40,
      first_name: 'Ree',
      last_name: 'Tyler',
      email: 'rtyler13@topsy.com',
      gender: 'Genderqueer',
      ip_address: '85.232.49.165',
      age: 50,
    },
    {
      id: 41,
      first_name: 'Darnell',
      last_name: 'Stanway',
      email: 'dstanway14@studiopress.com',
      gender: 'Male',
      ip_address: '162.204.181.92',
      age: 66,
    },
    {
      id: 42,
      first_name: 'Clerkclaude',
      last_name: 'Burgwyn',
      email: 'cburgwyn15@dagondesign.com',
      gender: 'Male',
      ip_address: '110.134.162.212',
      age: 13,
    },
    {
      id: 43,
      first_name: 'Melva',
      last_name: 'Schoffel',
      email: 'mschoffel16@flickr.com',
      gender: 'Female',
      ip_address: '213.78.112.171',
      age: 12,
    },
    {
      id: 44,
      first_name: 'Danie',
      last_name: 'Vasyatkin',
      email: 'dvasyatkin17@telegraph.co.uk',
      gender: 'Male',
      ip_address: '206.133.1.47',
      age: 6,
    },
    {
      id: 45,
      first_name: 'Jaquenette',
      last_name: 'Arghent',
      email: 'jarghent18@engadget.com',
      gender: 'Female',
      ip_address: '0.105.147.158',
      age: 30,
    },
    {
      id: 46,
      first_name: 'Feliza',
      last_name: 'Stoggell',
      email: 'fstoggell19@clickbank.net',
      gender: 'Female',
      ip_address: '197.210.157.240',
      age: 86,
    },
    {
      id: 47,
      first_name: 'Aylmer',
      last_name: 'Shepperd',
      email: 'ashepperd1a@guardian.co.uk',
      gender: 'Male',
      ip_address: '164.157.205.100',
      age: 53,
    },
    {
      id: 48,
      first_name: 'Aurore',
      last_name: 'Celier',
      email: 'acelier1b@nih.gov',
      gender: 'Female',
      ip_address: '172.141.116.150',
      age: 87,
    },
    {
      id: 49,
      first_name: 'Bartolemo',
      last_name: 'Phittiplace',
      email: 'bphittiplace1c@pcworld.com',
      gender: 'Male',
      ip_address: '155.76.126.52',
      age: 96,
    },
    {
      id: 50,
      first_name: 'Millie',
      last_name: 'Linsley',
      email: 'mlinsley1d@friendfeed.com',
      gender: 'Female',
      ip_address: '135.158.9.204',
      age: 48,
    },
    {
      id: 51,
      first_name: 'Agathe',
      last_name: 'Orae',
      email: 'aorae1e@mlb.com',
      gender: 'Female',
      ip_address: '85.28.102.29',
      age: 4,
    },
    {
      id: 52,
      first_name: 'Humfried',
      last_name: 'Maund',
      email: 'hmaund1f@ebay.co.uk',
      gender: 'Male',
      ip_address: '101.22.161.244',
      age: 98,
    },
    {
      id: 53,
      first_name: 'Floyd',
      last_name: 'Galey',
      email: 'fgaley1g@businessweek.com',
      gender: 'Male',
      ip_address: '87.132.110.230',
      age: 88,
    },
    {
      id: 54,
      first_name: 'Egor',
      last_name: 'Wakes',
      email: 'ewakes1h@foxnews.com',
      gender: 'Male',
      ip_address: '155.243.228.46',
      age: 1,
    },
    {
      id: 55,
      first_name: 'Trace',
      last_name: 'Gentsch',
      email: 'tgentsch1i@jugem.jp',
      gender: 'Male',
      ip_address: '230.23.105.255',
      age: 75,
    },
    {
      id: 56,
      first_name: 'Terrel',
      last_name: 'Greensides',
      email: 'tgreensides1j@youtube.com',
      gender: 'Male',
      ip_address: '142.203.72.96',
      age: 24,
    },
    {
      id: 57,
      first_name: 'Martynne',
      last_name: 'Geffen',
      email: 'mgeffen1k@a8.net',
      gender: 'Female',
      ip_address: '29.98.233.22',
      age: 72,
    },
    {
      id: 58,
      first_name: 'Orin',
      last_name: 'Yea',
      email: 'oyea1l@tmall.com',
      gender: 'Male',
      ip_address: '144.44.36.71',
      age: 41,
    },
    {
      id: 59,
      first_name: 'Cesar',
      last_name: 'Reardon',
      email: 'creardon1m@upenn.edu',
      gender: 'Male',
      ip_address: '191.79.55.5',
      age: 72,
    },
    {
      id: 60,
      first_name: 'Pollyanna',
      last_name: 'McPhelimey',
      email: 'pmcphelimey1n@fda.gov',
      gender: 'Female',
      ip_address: '73.43.97.90',
      age: 81,
    },
    {
      id: 61,
      first_name: 'Kendall',
      last_name: 'Walbrook',
      email: 'kwalbrook1o@vkontakte.ru',
      gender: 'Male',
      ip_address: '153.157.178.163',
      age: 28,
    },
    {
      id: 62,
      first_name: 'Iona',
      last_name: 'Shapiro',
      email: 'ishapiro1p@parallels.com',
      gender: 'Female',
      ip_address: '84.97.145.89',
      age: 12,
    },
    {
      id: 63,
      first_name: 'Loralie',
      last_name: 'Leagas',
      email: 'lleagas1q@dot.gov',
      gender: 'Female',
      ip_address: '228.223.159.100',
      age: 70,
    },
    {
      id: 64,
      first_name: 'Laurette',
      last_name: 'Rickert',
      email: 'lrickert1r@google.fr',
      gender: 'Female',
      ip_address: '201.158.72.31',
      age: 48,
    },
    {
      id: 65,
      first_name: 'Marissa',
      last_name: 'Scrimshaw',
      email: 'mscrimshaw1s@unc.edu',
      gender: 'Female',
      ip_address: '63.86.33.246',
      age: 79,
    },
    {
      id: 66,
      first_name: 'Isaiah',
      last_name: 'Fildery',
      email: 'ifildery1t@soup.io',
      gender: 'Male',
      ip_address: '186.37.214.72',
      age: 50,
    },
    {
      id: 67,
      first_name: 'Anatol',
      last_name: 'Goodrich',
      email: 'agoodrich1u@paginegialle.it',
      gender: 'Male',
      ip_address: '0.5.188.193',
      age: 16,
    },
    {
      id: 68,
      first_name: 'Carrol',
      last_name: 'Dudleston',
      email: 'cdudleston1v@princeton.edu',
      gender: 'Male',
      ip_address: '132.124.105.16',
      age: 93,
    },
    {
      id: 69,
      first_name: 'Kenton',
      last_name: 'Greggor',
      email: 'kgreggor1w@seesaa.net',
      gender: 'Male',
      ip_address: '179.42.23.39',
      age: 46,
    },
    {
      id: 70,
      first_name: 'Jacquenette',
      last_name: 'Witter',
      email: 'jwitter1x@businessweek.com',
      gender: 'Female',
      ip_address: '115.166.241.99',
      age: 96,
    },
    {
      id: 71,
      first_name: 'Pace',
      last_name: 'Bertot',
      email: 'pbertot1y@gizmodo.com',
      gender: 'Male',
      ip_address: '176.146.142.40',
      age: 36,
    },
    {
      id: 72,
      first_name: 'Sabina',
      last_name: 'Chesnut',
      email: 'schesnut1z@nifty.com',
      gender: 'Female',
      ip_address: '123.54.219.171',
      age: 97,
    },
    {
      id: 73,
      first_name: 'Rosmunda',
      last_name: 'Rayment',
      email: 'rrayment20@weather.com',
      gender: 'Female',
      ip_address: '137.16.221.4',
      age: 63,
    },
    {
      id: 74,
      first_name: 'Georges',
      last_name: 'Vinden',
      email: 'gvinden21@slashdot.org',
      gender: 'Male',
      ip_address: '27.141.144.9',
      age: 60,
    },
    {
      id: 75,
      first_name: 'Nathan',
      last_name: 'Senett',
      email: 'nsenett22@home.pl',
      gender: 'Male',
      ip_address: '74.56.15.144',
      age: 89,
    },
    {
      id: 76,
      first_name: 'Alfie',
      last_name: 'Antonsson',
      email: 'aantonsson23@deliciousdays.com',
      gender: 'Male',
      ip_address: '68.105.170.47',
      age: 61,
    },
    {
      id: 77,
      first_name: 'Pietrek',
      last_name: 'Kleynen',
      email: 'pkleynen24@plala.or.jp',
      gender: 'Male',
      ip_address: '236.155.84.206',
      age: 37,
    },
    {
      id: 78,
      first_name: 'Cassandry',
      last_name: 'Bearman',
      email: 'cbearman25@mysql.com',
      gender: 'Bigender',
      ip_address: '195.97.134.42',
      age: 74,
    },
    {
      id: 79,
      first_name: 'Janella',
      last_name: 'Daniello',
      email: 'jdaniello26@com.com',
      gender: 'Female',
      ip_address: '182.174.61.158',
      age: 98,
    },
    {
      id: 80,
      first_name: 'Francis',
      last_name: 'Sedgeman',
      email: 'fsedgeman27@theatlantic.com',
      gender: 'Male',
      ip_address: '15.119.13.65',
      age: 79,
    },
    {
      id: 81,
      first_name: 'Wally',
      last_name: 'Derby',
      email: 'wderby28@friendfeed.com',
      gender: 'Female',
      ip_address: '96.213.127.19',
      age: 13,
    },
    {
      id: 82,
      first_name: 'Edd',
      last_name: 'Romera',
      email: 'eromera29@geocities.jp',
      gender: 'Agender',
      ip_address: '194.117.57.17',
      age: 99,
    },
    {
      id: 83,
      first_name: 'Kimball',
      last_name: 'Caldaro',
      email: 'kcaldaro2a@cocolog-nifty.com',
      gender: 'Male',
      ip_address: '73.224.29.122',
      age: 84,
    },
    {
      id: 84,
      first_name: 'Phyllis',
      last_name: 'Scartifield',
      email: 'pscartifield2b@unesco.org',
      gender: 'Female',
      ip_address: '58.41.222.196',
      age: 39,
    },
    {
      id: 85,
      first_name: 'Bernadene',
      last_name: 'Churchouse',
      email: 'bchurchouse2c@paypal.com',
      gender: 'Female',
      ip_address: '79.242.155.150',
      age: 66,
    },
    {
      id: 86,
      first_name: 'Jamaal',
      last_name: 'Bilovsky',
      email: 'jbilovsky2d@msn.com',
      gender: 'Male',
      ip_address: '136.17.28.100',
      age: 85,
    },
    {
      id: 87,
      first_name: 'Lyn',
      last_name: 'Hathway',
      email: 'lhathway2e@google.ca',
      gender: 'Male',
      ip_address: '194.179.56.114',
      age: 36,
    },
    {
      id: 88,
      first_name: 'Siouxie',
      last_name: 'Ralestone',
      email: 'sralestone2f@epa.gov',
      gender: 'Polygender',
      ip_address: '53.176.158.27',
      age: 83,
    },
    {
      id: 89,
      first_name: 'Verge',
      last_name: 'Hadlington',
      email: 'vhadlington2g@vinaora.com',
      gender: 'Male',
      ip_address: '178.156.135.218',
      age: 98,
    },
    {
      id: 90,
      first_name: 'Tatiania',
      last_name: 'Clery',
      email: 'tclery2h@cdc.gov',
      gender: 'Female',
      ip_address: '229.249.182.23',
      age: 92,
    },
    {
      id: 91,
      first_name: 'Hamid',
      last_name: 'Loveitt',
      email: 'hloveitt2i@illinois.edu',
      gender: 'Male',
      ip_address: '144.159.71.12',
      age: 85,
    },
    {
      id: 92,
      first_name: 'Juditha',
      last_name: 'Tackes',
      email: 'jtackes2j@paypal.com',
      gender: 'Female',
      ip_address: '250.251.210.219',
      age: 28,
    },
    {
      id: 93,
      first_name: 'Tallia',
      last_name: 'Cosans',
      email: 'tcosans2k@free.fr',
      gender: 'Female',
      ip_address: '135.200.195.172',
      age: 10,
    },
    {
      id: 94,
      first_name: 'Evonne',
      last_name: 'MacKerley',
      email: 'emackerley2l@soup.io',
      gender: 'Female',
      ip_address: '245.42.245.19',
      age: 90,
    },
    {
      id: 95,
      first_name: 'Ker',
      last_name: 'Ivanovic',
      email: 'kivanovic2m@blogs.com',
      gender: 'Male',
      ip_address: '103.151.207.234',
      age: 97,
    },
    {
      id: 96,
      first_name: 'Lee',
      last_name: 'Crotch',
      email: 'lcrotch2n@digg.com',
      gender: 'Male',
      ip_address: '93.170.172.127',
      age: 60,
    },
    {
      id: 97,
      first_name: 'Brittani',
      last_name: 'Owain',
      email: 'bowain2o@elegantthemes.com',
      gender: 'Female',
      ip_address: '190.239.249.115',
      age: 94,
    },
    {
      id: 98,
      first_name: 'Franklin',
      last_name: 'Beagley',
      email: 'fbeagley2p@cnbc.com',
      gender: 'Male',
      ip_address: '237.203.113.57',
      age: 68,
    },
    {
      id: 99,
      first_name: 'Granthem',
      last_name: 'Brasher',
      email: 'gbrasher2q@free.fr',
      gender: 'Male',
      ip_address: '22.229.203.125',
      age: 31,
    },
    {
      id: 100,
      first_name: 'Arabel',
      last_name: 'Slidders',
      email: 'aslidders2r@bbc.co.uk',
      gender: 'Female',
      ip_address: '238.35.111.128',
      age: 96,
    },
  ]

  const rowSelection: RowSelectionProps = {
    onChange: (selectedRowKeys: React.Key[], selectedRows: DataType[]) => {
      console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows)
    },
    getCheckboxProps: (record: DataType) => ({
      disabled: record.first_name === 'Disabled User',
      name: record.first_name,
    }),
    selectionType: 'checkbox',
  }

  const userTable: TableProps = {
    columns,
    data,
    isStickyHeader: true,
    rowSelection,
  }

  return (
    <div>
      <div>
        <h2>TextBox</h2>
        <TextBox {...txtNameSurname} />
      </div>
      <hr />
      <div>
        <h2>TextBox Number</h2>
        <TextBox {...txtBirthYear} />
      </div>
      <hr />
      <div>
        <h2>Datepicker</h2>
        <DatePicker {...dpBirthDate} />
      </div>
      <hr />
      <div>
        <h2>Table</h2>
        <Table {...userTable} />
      </div>
    </div>
  )
}

export default App
